# Analysis of Covid Data

In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('covid_data.csv', encoding='latin-1')

In [3]:
df.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time
0,North-America,Anguilla,15230.0,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,788.0,12.0,3373736.0,51382.0,07-07-2023,2023-07-07T17:30:09+00:00
1,North-America,Saint-Pierre-Miquelon,5759.0,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,347.0,2.0,4410488.0,25400.0,07-07-2023,2023-07-07T17:30:09+00:00
2,Africa,Saint-Helena,6115.0,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00
4,North-America,Montserrat,4965.0,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00

# Cleaning of the Dataset

## There are certain records in the dataset where the country is same as the continent. So we must clean the data by dropping those records.

In [5]:
df.drop(df[df['Country'] == 'Europe'].index, inplace = True)

In [6]:
df.drop(df[df['Country'] == 'Asia'].index, inplace = True)

In [7]:
df.drop(df[df['Country'] == 'Africa'].index, inplace = True)

In [8]:
df.drop(df[df['Country'] == 'North-America'].index, inplace = True)

In [9]:
df.drop(df[df['Country'] == 'South-America'].index, inplace = True)

In [10]:
df.drop(df[df['Country'] == 'Oceania'].index, inplace = True)

In [12]:
df.drop(df[df['Country'] == 'All'].index, inplace = True)

In [13]:
df

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time
0,North-America,Anguilla,15230.0,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,788.0,12.0,3373736.0,51382.0,07-07-2023,2023-07-07T17:30:09+00:00
1,North-America,Saint-Pierre-Miquelon,5759.0,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,347.0,2.0,4410488.0,25400.0,07-07-2023,2023-07-07T17:30:09+00:00
2,Africa,Saint-Helena,6115.0,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00
4,North-America,Montserrat,4965.0,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Asia,Vietnam,98953541.0,57.0,937577.0,3.0,10640164.0,117438.0,11620947,NaN,437.0,43206.0,867342.0,85826548.0,07-07-2023,2023-07-07T17:30:06+00:00
227,Asia,Philippines,112508994.0,397.0,6637.0,162.0,4094138.0,37039.0,4167259,NaN,591.0,66484.0,315520.0,35498885.0,07-07-2023,2023-07-07T17:30:06+00:00
228,Europe,Denmark,5834950.0,5.0,86.0,4.0,3173458.0,545386.0,3182299,NaN,1500.0,8755.0,22160238.0,129303879.0,07-07-2023,2023-07-07T17:30:06+00:00
229,Asia,Hong-Kong,7604299.0,1102.0,6104.0,28.0,2893532.0,383133.0,2913455,NaN,1817.0,13819.0,10011143.0,76127725.0,07-07-2023,2023-07-07T17:30:06+00:00
230,Europe,Czechia,10736784.0,5.0,182.0,1.0,4599798.0,432419.0,4642791,NaN,3987.0,42811.0,5330723.0,57234819.0,07-07-2023,2023-07-07T17:30:06+00:00

# Which is the most populous country?

In [14]:
df.sort_values('Population', ascending = False).head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time
9,Asia,China,1.448471e+09,NaN,118977.0,NaN,379053.0,347.0,503302,NaN,4.0,5272.0,110461.0,1.600000e+08,07-07-2023,2023-07-07T17:30:09+00:00
200,Asia,India,1.406632e+09,NaN,1453.0,NaN,44461044.0,31987.0,44994407,NaN,378.0,531910.0,661721.0,9.307980e+08,07-07-2023,2023-07-07T17:30:06+00:00
216,North-America,USA,3.348053e+08,NaN,674040.0,779.0,105509635.0,320641.0,107352160,NaN,3490.0,1168485.0,3526935.0,1.180836e+09,07-07-2023,2023-07-07T17:30:06+00:00
193,Asia,Indonesia,2.791345e+08,40.0,8245.0,NaN,6642003.0,24404.0,6812127,3.0,580.0,161879.0,408975.0,1.141589e+08,07-07-2023,2023-07-07T17:30:06+00:00
195,Asia,Pakistan,2.294890e+08,21.0,11882.0,2.0,1538689.0,6890.0,1581232,NaN,134.0,30661.0,133215.0,3.057138e+07,07-07-2023,2023-07-07T17:30:06+00:00

## So it can be seen the China is the most populous country in the world.

# Which is the least populous country?

In [15]:
df.sort_values('Population', ascending = True).head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time
6,Europe,Vatican-City,799.0,NaN,0.0,NaN,29.0,36295.0,29,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00
15,Oceania,Tokelau,1378.0,NaN,23.0,NaN,NaN,16691.0,23,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00
19,Oceania,Niue,1622.0,1.0,1.0,NaN,820.0,506165.0,821,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00
4,North-America,Montserrat,4965.0,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00

## So it can be seen that Vatican-City is the least populous country in the world.

# What percentage of the country's population was infected?

In [126]:
df['Percentage_Infected = (Cases.Total/Population)*100']=(df['Cases.Total']/df['Population'])*100

In [130]:
df.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100
0,North-America,Anguilla,15230.0,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,788.0,12.0,3373736.0,51382.0,07-07-2023,2023-07-07T17:30:09+00:00,25.633618
1,North-America,Saint-Pierre-Miquelon,5759.0,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,347.0,2.0,4410488.0,25400.0,07-07-2023,2023-07-07T17:30:09+00:00,59.940962
2,Africa,Saint-Helena,6115.0,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,35.421096
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179
4,North-America,Montserrat,4965.0,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00,28.257805

# Rank the countries on the basis of percentage infected and find out which country has the most percentage of infection.

In [133]:
df1 = df.sort_values('Percentage_Infected = (Cases.Total/Population)*100', ascending = False)

In [134]:
df1.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100
74,Europe,San-Marino,34085.0,7.0,5.0,4.0,24196.0,713686.0,24326,NaN,3667.0,125.0,5775414.0,196855.0,07-07-2023,2023-07-07T17:30:08+00:00,71.368637
23,Europe,Faeroe-Islands,49233.0,NaN,NaN,5.0,NaN,703959.0,34658,NaN,569.0,28.0,15802409.0,778000.0,07-07-2023,2023-07-07T17:30:08+00:00,70.395873
122,Asia,Brunei,445431.0,NaN,64951.0,3.0,243601.0,693209.0,308777,NaN,505.0,225.0,1611437.0,717784.0,07-07-2023,2023-07-07T17:30:07+00:00,69.320950
184,Europe,Austria,9066710.0,99.0,3811.0,14.0,6054934.0,670727.0,6081287,NaN,2486.0,22542.0,23302116.0,211273524.0,07-07-2023,2023-07-07T17:30:06+00:00,67.072698
209,Europe,Slovenia,2078034.0,6.0,81.0,8.0,1337079.0,646890.0,1344260,NaN,3417.0,7100.0,1370382.0,2847701.0,07-07-2023,2023-07-07T17:30:06+00:00,64.689028

In [135]:
Data_percent_infected = df1[['Country']]

In [136]:
Data_percent_infected.head()

            Country
74       San-Marino
23   Faeroe-Islands
122          Brunei
184         Austria
209        Slovenia

In [137]:
Data_percent_infected['Rank(basis: percent_infected)'] = [i for i in range(1,len(Data_percent_infected)+1)]

<ipython-input-137-491ada774c6e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data_percent_infected['Rank(basis: percent_infected)'] = [i for i in range(1,len(Data_percent_infected)+1)]

In [138]:
Data_percent_infected.head()

            Country  Rank(basis: percent_infected)
74       San-Marino                              1
23   Faeroe-Islands                              2
122          Brunei                              3
184         Austria                              4
209        Slovenia                              5

In [139]:
Ranked_Data = df.merge(Data_percent_infected, on='Country')

In [140]:
Ranked_Data.head(10)

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected)
0,North-America,Anguilla,1.523000e+04,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,788.0,12.0,3373736.0,51382.0,07-07-2023,2023-07-07T17:30:09+00:00,25.633618,79
1,North-America,Saint-Pierre-Miquelon,5.759000e+03,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,347.0,2.0,4410488.0,25400.0,07-07-2023,2023-07-07T17:30:09+00:00,59.940962,12
2,Africa,Saint-Helena,6.115000e+03,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,35.421096,53
3,South-America,Falkland-Islands,3.539000e+03,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19
4,North-America,Montserrat,4.965000e+03,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00,28.257805,68
5,NaN,Diamond-Princess,NaN,NaN,0.0,NaN,699.0,NaN,712,NaN,NaN,13.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,230
6,Europe,Vatican-City,7.990000e+02,NaN,0.0,NaN,29.0,36295.0,29,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,3.629537,156
7,Africa,Western-Sahara,6.261610e+05,NaN,0.0,NaN,9.0,16.0,10,NaN,2.0,1.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,0.001597,229
8,NaN,MS-Zaandam,NaN,NaN,0.0,NaN,7.0,NaN,9,NaN,NaN,2.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,231
9,Asia,China,1.448471e+09,NaN,118977.0,NaN,379053.0,347.0,503302,NaN,4.0,5272.0,110461.0,160000000.0,07-07-2023,2023-07-07T17:30:09+00:00,0.034747,228

## The above dataframe (Ranked_Data) shows the rank of each country on the basis of percentage of the population infected.

In [141]:
Ranked_Data[Ranked_Data['Rank(basis: percent_infected)']==1]

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected)
74,Europe,San-Marino,34085.0,7.0,5.0,4.0,24196.0,713686.0,24326,NaN,3667.0,125.0,5775414.0,196855.0,07-07-2023,2023-07-07T17:30:08+00:00,71.368637,1

## So it can be seen that San-Marino has the highest infection percentage.

# Rank the countries on the basis of total cases (decreasing order) and find out which country has the highest total infection cases.

In [142]:
df2 = df.sort_values('Cases.Total', ascending = False)

In [143]:
df2.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100
216,North-America,USA,3.348053e+08,NaN,674040.0,779.0,105509635.0,320641.0,107352160,NaN,3490.0,1168485.0,3526935.0,1.180836e+09,07-07-2023,2023-07-07T17:30:06+00:00,32.064059
200,Asia,India,1.406632e+09,NaN,1453.0,NaN,44461044.0,31987.0,44994407,NaN,378.0,531910.0,661721.0,9.307980e+08,07-07-2023,2023-07-07T17:30:06+00:00,3.198734
217,Europe,France,6.558452e+07,NaN,16503.0,869.0,39954415.0,612013.0,40138560,NaN,2556.0,167642.0,4139547.0,2.714902e+08,07-07-2023,2023-07-07T17:30:06+00:00,61.201273
175,Europe,Germany,8.388360e+07,NaN,13733.0,NaN,38240600.0,458119.0,38428685,NaN,2078.0,174352.0,1458359.0,1.223324e+08,07-07-2023,2023-07-07T17:30:06+00:00,45.811919
198,South-America,Brazil,2.153536e+08,1606.0,729340.0,NaN,36249161.0,174980.0,37682660,28.0,3270.0,704159.0,296146.0,6.377617e+07,07-07-2023,2023-07-07T17:30:06+00:00,17.498041

In [144]:
Data_total_cases = df2[['Country']]

In [145]:
Data_total_cases.head()

     Country
216      USA
200    India
217   France
175  Germany
198   Brazil

In [146]:
Data_total_cases['Rank(basis: total_cases)'] = [i for i in range(1,len(Data_total_cases)+1)]

<ipython-input-146-79512669c78b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data_total_cases['Rank(basis: total_cases)'] = [i for i in range(1,len(Data_total_cases)+1)]

In [147]:
Data_total_cases.head()

     Country  Rank(basis: total_cases)
216      USA                         1
200    India                         2
217   France                         3
175  Germany                         4
198   Brazil                         5

In [148]:
Ranked_Data_2 = Ranked_Data.merge(Data_total_cases, on='Country')

In [149]:
Ranked_Data_2.head(10)

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases)
0,North-America,Anguilla,1.523000e+04,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,788.0,12.0,3373736.0,51382.0,07-07-2023,2023-07-07T17:30:09+00:00,25.633618,79,219
1,North-America,Saint-Pierre-Miquelon,5.759000e+03,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,347.0,2.0,4410488.0,25400.0,07-07-2023,2023-07-07T17:30:09+00:00,59.940962,12,221
2,Africa,Saint-Helena,6.115000e+03,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,35.421096,53,223
3,South-America,Falkland-Islands,3.539000e+03,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19,224
4,North-America,Montserrat,4.965000e+03,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00,28.257805,68,225
5,NaN,Diamond-Princess,NaN,NaN,0.0,NaN,699.0,NaN,712,NaN,NaN,13.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,230,227
6,Europe,Vatican-City,7.990000e+02,NaN,0.0,NaN,29.0,36295.0,29,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,3.629537,156,228
7,Africa,Western-Sahara,6.261610e+05,NaN,0.0,NaN,9.0,16.0,10,NaN,2.0,1.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,0.001597,229,230
8,NaN,MS-Zaandam,NaN,NaN,0.0,NaN,7.0,NaN,9,NaN,NaN,2.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,231,231
9,Asia,China,1.448471e+09,NaN,118977.0,NaN,379053.0,347.0,503302,NaN,4.0,5272.0,110461.0,160000000.0,07-07-2023,2023-07-07T17:30:09+00:00,0.034747,228,92

## The above dataframe (Ranked_Data_2) shows the rank of each country on the basis of total cases of infection.

In [150]:
Ranked_Data_2[Ranked_Data_2['Rank(basis: total_cases)']==1]

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases)
216,North-America,USA,334805269.0,NaN,674040.0,779.0,105509635.0,320641.0,107352160,NaN,3490.0,1168485.0,3526935.0,1.180836e+09,07-07-2023,2023-07-07T17:30:06+00:00,32.064059,59,1

## So it can be seen that USA has the most number of total cases of infection.

# Rank the countries on the basis of fatality rate (i.e. what percentage of the total infected people died) - in descending order

In [153]:
Ranked_Data_2['Fatality_Rate = (Deaths.Total/Cases.Total)*100']=(df['Deaths.Total']/df['Cases.Total'])*100

In [154]:
Ranked_Data_2.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100
0,North-America,Anguilla,15230.0,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,788.0,12.0,3373736.0,51382.0,07-07-2023,2023-07-07T17:30:09+00:00,25.633618,79,219,0.307377
1,North-America,Saint-Pierre-Miquelon,5759.0,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,347.0,2.0,4410488.0,25400.0,07-07-2023,2023-07-07T17:30:09+00:00,59.940962,12,221,0.057937
2,Africa,Saint-Helena,6115.0,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,35.421096,53,223,NaN
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19,224,NaN
4,North-America,Montserrat,4965.0,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00,28.257805,68,225,0.570207

In [155]:
df3=Ranked_Data_2.sort_values('Fatality_Rate = (Deaths.Total/Cases.Total)*100', ascending = False)

In [156]:
df3.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,Deaths.1M_pop,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100
8,NaN,MS-Zaandam,NaN,NaN,0.0,NaN,7.0,NaN,9,NaN,NaN,2.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,231,231,22.222222
34,Asia,Yemen,31154867.0,NaN,662.0,23.0,9124.0,383.0,11945,NaN,69.0,2159.0,10579.0,329592.0,07-07-2023,2023-07-07T17:30:08+00:00,0.038341,226,198,18.074508
7,Africa,Western-Sahara,626161.0,NaN,0.0,NaN,9.0,16.0,10,NaN,2.0,1.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,0.001597,229,230,10.000000
83,Africa,Sudan,45992020.0,NaN,184.0,NaN,58763.0,1391.0,63993,NaN,110.0,5046.0,12240.0,562941.0,07-07-2023,2023-07-07T17:30:08+00:00,0.139139,219,146,7.885237
81,Asia,Syria,19364809.0,5.0,0.0,NaN,54504.0,2978.0,57669,NaN,163.0,3165.0,7553.0,146269.0,07-07-2023,2023-07-07T17:30:08+00:00,0.297803,207,149,5.488217

In [157]:
Data_fatality_rate = df3[['Country']]

In [158]:
Data_fatality_rate.head()

           Country
8       MS-Zaandam
34           Yemen
7   Western-Sahara
83           Sudan
81           Syria

In [159]:
Data_fatality_rate['Rank(basis: fatality_rate)'] = [i for i in range(1,len(Data_fatality_rate)+1)]

<ipython-input-159-a2cc381cc766>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data_fatality_rate['Rank(basis: fatality_rate)'] = [i for i in range(1,len(Data_fatality_rate)+1)]

In [160]:
Data_fatality_rate.head()

           Country  Rank(basis: fatality_rate)
8       MS-Zaandam                           1
34           Yemen                           2
7   Western-Sahara                           3
83           Sudan                           4
81           Syria                           5

In [161]:
Ranked_Data_3 = Ranked_Data_2.merge(Data_fatality_rate, on='Country')

In [162]:
Ranked_Data_3.head(10)

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,...,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100,Rank(basis: fatality_rate)
0,North-America,Anguilla,1.523000e+04,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,...,12.0,3373736.0,51382.0,07-07-2023,2023-07-07T17:30:09+00:00,25.633618,79,219,0.307377,188
1,North-America,Saint-Pierre-Miquelon,5.759000e+03,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,...,2.0,4410488.0,25400.0,07-07-2023,2023-07-07T17:30:09+00:00,59.940962,12,221,0.057937,221
2,Africa,Saint-Helena,6.115000e+03,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,...,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,35.421096,53,223,NaN,227
3,South-America,Falkland-Islands,3.539000e+03,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,...,NaN,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19,224,NaN,228
4,North-America,Montserrat,4.965000e+03,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,...,8.0,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00,28.257805,68,225,0.570207,156
5,NaN,Diamond-Princess,NaN,NaN,0.0,NaN,699.0,NaN,712,NaN,...,13.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,230,227,1.825843,57
6,Europe,Vatican-City,7.990000e+02,NaN,0.0,NaN,29.0,36295.0,29,NaN,...,NaN,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,3.629537,156,228,NaN,229
7,Africa,Western-Sahara,6.261610e+05,NaN,0.0,NaN,9.0,16.0,10,NaN,...,1.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,0.001597,229,230,10.000000,3
8,NaN,MS-Zaandam,NaN,NaN,0.0,NaN,7.0,NaN,9,NaN,...,2.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,231,231,22.222222,1
9,Asia,China,1.448471e+09,NaN,118977.0,NaN,379053.0,347.0,503302,NaN,...,5272.0,110461.0,160000000.0,07-07-2023,2023-07-07T17:30:09+00:00,0.034747,228,92,1.047482,103

## The above dataframe (Ranked_Data_3) shows the rank of each country on the basis of fatality rate.

In [163]:
Ranked_Data_3[Ranked_Data_3['Rank(basis: fatality_rate)']==1]

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,...,Deaths.Total,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100,Rank(basis: fatality_rate)
8,NaN,MS-Zaandam,NaN,NaN,0.0,NaN,7.0,NaN,9,NaN,...,2.0,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,231,231,22.222222,1

## So it can be seen that MS-Zaandam has suffered the highest fatality rate.

# Rank the countries on the basis of recovery rate (i.e. percentage of the total infected people recovered) and find out which country has the highest recovery rate - in decreasing order

In [164]:
Ranked_Data_3['Recovery_Rate = (Cases.Recovered)/Cases.Total)*100']=(df['Cases.Recovered']/df['Cases.Total'])*100

In [165]:
Ranked_Data_3.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,...,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100,Rank(basis: fatality_rate),Recovery_Rate = (Cases.Recovered)/Cases.Total)*100
0,North-America,Anguilla,15230.0,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,...,3373736.0,51382.0,07-07-2023,2023-07-07T17:30:09+00:00,25.633618,79,219,0.307377,188,99.359631
1,North-America,Saint-Pierre-Miquelon,5759.0,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,...,4410488.0,25400.0,07-07-2023,2023-07-07T17:30:09+00:00,59.940962,12,221,0.057937,221,70.944380
2,Africa,Saint-Helena,6115.0,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,...,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,35.421096,53,223,NaN,227,0.092336
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,...,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19,224,NaN,228,100.000000
4,North-America,Montserrat,4965.0,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,...,3577442.0,17762.0,07-07-2023,2023-07-07T17:30:09+00:00,28.257805,68,225,0.570207,156,98.075552

In [166]:
df4 = Ranked_Data_3.sort_values('Recovery_Rate = (Cases.Recovered)/Cases.Total)*100', ascending = False)

In [167]:
df4.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,...,Tests.1M_pop,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100,Rank(basis: fatality_rate),Recovery_Rate = (Cases.Recovered)/Cases.Total)*100
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,...,2439107.0,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19,224,NaN,228,100.000000
6,Europe,Vatican-City,799.0,NaN,0.0,NaN,29.0,36295.0,29,NaN,...,NaN,NaN,07-07-2023,2023-07-07T17:30:09+00:00,3.629537,156,228,NaN,229,100.000000
166,Asia,DPRK,25990679.0,NaN,0.0,NaN,4772739.0,183636.0,4772813,NaN,...,NaN,NaN,07-07-2023,2023-07-07T17:30:06+00:00,18.363556,93,31,0.001550,226,99.998450
75,Oceania,Cook-Islands,17571.0,2.0,4.0,NaN,7138.0,406579.0,7144,NaN,...,1120596.0,19690.0,07-07-2023,2023-07-07T17:30:08+00:00,40.657902,48,211,0.027996,224,99.916013
65,Oceania,Marshall-Islands,60057.0,17.0,2.0,NaN,16079.0,268045.0,16098,NaN,...,NaN,NaN,07-07-2023,2023-07-07T17:30:08+00:00,26.804536,76,189,0.105603,215,99.881973

In [168]:
Data_recovery_rate = df4[['Country']]

In [169]:
Data_recovery_rate.head()

              Country
3    Falkland-Islands
6        Vatican-City
166              DPRK
75       Cook-Islands
65   Marshall-Islands

In [170]:
Data_recovery_rate['Rank(basis: recovery_rate)'] = [i for i in range(1,len(Data_recovery_rate)+1)]

<ipython-input-170-fccbe9c75664>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data_recovery_rate['Rank(basis: recovery_rate)'] = [i for i in range(1,len(Data_recovery_rate)+1)]

In [171]:
Data_recovery_rate.head()

              Country  Rank(basis: recovery_rate)
3    Falkland-Islands                           1
6        Vatican-City                           2
166              DPRK                           3
75       Cook-Islands                           4
65   Marshall-Islands                           5

In [172]:
Ranked_Data_4 = Ranked_Data_3.merge(Data_recovery_rate, on='Country')

In [173]:
Ranked_Data_4.head()

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,...,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100,Rank(basis: fatality_rate),Recovery_Rate = (Cases.Recovered)/Cases.Total)*100,Rank(basis: recovery_rate)
0,North-America,Anguilla,15230.0,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,...,51382.0,07-07-2023,2023-07-07T17:30:09+00:00,25.633618,79,219,0.307377,188,99.359631,35
1,North-America,Saint-Pierre-Miquelon,5759.0,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,...,25400.0,07-07-2023,2023-07-07T17:30:09+00:00,59.940962,12,221,0.057937,221,70.944380,193
2,Africa,Saint-Helena,6115.0,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,...,NaN,07-07-2023,2023-07-07T17:30:09+00:00,35.421096,53,223,NaN,227,0.092336,209
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,...,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19,224,NaN,228,100.000000,1
4,North-America,Montserrat,4965.0,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,...,17762.0,07-07-2023,2023-07-07T17:30:09+00:00,28.257805,68,225,0.570207,156,98.075552,111

## The above dataframe shows the rank of the countries on the basis of the recovery rate.

In [174]:
Ranked_Data_4[Ranked_Data_4['Rank(basis: recovery_rate)']==1]

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,...,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100,Rank(basis: fatality_rate),Recovery_Rate = (Cases.Recovered)/Cases.Total)*100,Rank(basis: recovery_rate)
3,South-America,Falkland-Islands,3539.0,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,...,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19,224,NaN,228,100.0,1

## So it can be seen that Falkland-Islands has the highest recovery rate.

In [178]:
Final_Data = Ranked_Data_4

# Final Dataset

In [182]:
Final_Data.head(10)

,Continent,Country,Population,Cases.New,Cases.Active,Cases.Critical,Cases.Recovered,Cases.1M_pop,Cases.Total,Deaths.New,...,Tests.Total,Day,Time,Percentage_Infected = (Cases.Total/Population)*100,Rank(basis: percent_infected),Rank(basis: total_cases),Fatality_Rate = (Deaths.Total/Cases.Total)*100,Rank(basis: fatality_rate),Recovery_Rate = (Cases.Recovered)/Cases.Total)*100,Rank(basis: recovery_rate)
0,North-America,Anguilla,1.523000e+04,NaN,13.0,4.0,3879.0,256336.0,3904,NaN,...,51382.0,07-07-2023,2023-07-07T17:30:09+00:00,25.633618,79,219,0.307377,188,99.359631,35
1,North-America,Saint-Pierre-Miquelon,5.759000e+03,NaN,1001.0,1.0,2449.0,599410.0,3452,NaN,...,25400.0,07-07-2023,2023-07-07T17:30:09+00:00,59.940962,12,221,0.057937,221,70.944380,193
2,Africa,Saint-Helena,6.115000e+03,NaN,2164.0,NaN,2.0,354211.0,2166,NaN,...,NaN,07-07-2023,2023-07-07T17:30:09+00:00,35.421096,53,223,NaN,227,0.092336,209
3,South-America,Falkland-Islands,3.539000e+03,NaN,0.0,NaN,1930.0,545352.0,1930,NaN,...,8632.0,07-07-2023,2023-07-07T17:30:09+00:00,54.535179,19,224,NaN,228,100.000000,1
4,North-America,Montserrat,4.965000e+03,NaN,19.0,NaN,1376.0,282578.0,1403,NaN,...,17762.0,07-07-2023,2023-07-07T17:30:09+00:00,28.257805,68,225,0.570207,156,98.075552,111
5,NaN,Diamond-Princess,NaN,NaN,0.0,NaN,699.0,NaN,712,NaN,...,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,230,227,1.825843,57,98.174157,105
6,Europe,Vatican-City,7.990000e+02,NaN,0.0,NaN,29.0,36295.0,29,NaN,...,NaN,07-07-2023,2023-07-07T17:30:09+00:00,3.629537,156,228,NaN,229,100.000000,2
7,Africa,Western-Sahara,6.261610e+05,NaN,0.0,NaN,9.0,16.0,10,NaN,...,NaN,07-07-2023,2023-07-07T17:30:09+00:00,0.001597,229,230,10.000000,3,90.000000,174
8,NaN,MS-Zaandam,NaN,NaN,0.0,NaN,7.0,NaN,9,NaN,...,NaN,07-07-2023,2023-07-07T17:30:09+00:00,NaN,231,231,22.222222,1,77.777778,189
9,Asia,China,1.448471e+09,NaN,118977.0,NaN,379053.0,347.0,503302,NaN,...,160000000.0,07-07-2023,2023-07-07T17:30:09+00:00,0.034747,228,92,1.047482,103,75.313231,191